tracker_type: botsort
track_high_thresh: 0.6
track_low_thresh: 0.1
new_track_thresh: 0.7
track_buffer: 30
match_thresh: 0.8
fuse_score: True
gmc_method: sparseOptFlow
proximity_thresh: 0.5
appearance_thresh: 0.25
with_reid: True
model: 'E:/Documenti/UniTo/Lab modigliani/Exp/BW_2025/TobiiPro Lab/Hermes v1/Prove/prova7/Bwww/assets/models/resnet50_msmt17_ready.pt'